<a href="https://colab.research.google.com/github/jandoniec/ProcessingDataInSocialSciences/blob/main/praca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The employees.csv file contains data about employees. Using Power Query, import the data into a spreadsheet. Then:

display the sorted the data by salary, starting with the highest
display employees from Poland, aged at least 50 years
calculate the number of women younger than 50

In [5]:
import pandas as pd

In [6]:
employees = pd.read_csv('employees.csv')
employees.sort_values('salary', ascending=False)

,first_name,last_name,sex,age,country,job_title,start_date,salary
0,Lucho,Maytum,Male,37,United Kingdom,Mechanical Systems Engineer,2/10/2016,148308.96
5,Sadella,Batterham,Female,37,Czech Republic,Assistant Media Planner,1/14/2017,136875.05
2,Missie,Kulic,Female,49,Poland,Business Systems Development Analyst,2/21/2015,133566.77
4,Gawen,Richarz,Male,50,Poland,Senior Cost Accountant,7/19/2019,115606.12
11,Annemarie,Albers,Female,50,Poland,Structural Analysis Engineer,3/12/2020,109840.09
18,Rochella,Slym,Female,19,Poland,Account Representative I,10/5/2019,105826.54
15,Ettore,Ernke,Male,49,Poland,Environmental Specialist,3/14/2022,103866.10
8,Dolph,Mesnard,Male,53,Czech Republic,Automation Specialist II,7/21/2012,82159.90
7,Obidiah,Bradburn,Male,49,Czech Republic,Geological Engineer,12/2/2010,64912.33
9,Fabien,McLanaghan,Male,48,Czech Republic,Graphic Designer,12/1/2021,63059.52
17,Courtnay,Creevy,Male,61,Czech Republic,Legal Assistant,1/14/2015,57492.08
1,Torrance,Brandi,Male,60,Czech Republic,Paralegal,8/12/2020,57026.74
3,Rickie,Somerville,Male,39,Czech Republic,Speech Pathologist,3/11/2014,53750.68
6,Meghann,Dance,Female,20,Czech Republic,Media Manager II,6/10/2014,44973.70
14,Osbourne,Rawet,Male,50,Poland,Office Assistant III,8/12/2021,41511.02
16,Mortie,Goodayle,Male,56,Czech Republic,Product Engineer,5/18/2011,40060.88
19,Frannie,McMorran,Male,47,Poland,Budget/Accounting Analyst II,3/31/2020,39107.88
13,Loydie,Cubbinelli,Male,35,Czech Republic,Systems Administrator IV,5/13/2014,34415.64
12,Erinn,Borell,Female,36,Czech Republic,Help Desk Technician,11/6/2011,22500.03
10,Shaina,Gaveltone,Female,58,Poland,Web Designer II,9/12/2010,21228.29

In [7]:
employees.loc[(employees['country'] == 'Poland') & (employees['age'] >= 50)]

,first_name,last_name,sex,age,country,job_title,start_date,salary
4,Gawen,Richarz,Male,50,Poland,Senior Cost Accountant,7/19/2019,115606.12
10,Shaina,Gaveltone,Female,58,Poland,Web Designer II,9/12/2010,21228.29
11,Annemarie,Albers,Female,50,Poland,Structural Analysis Engineer,3/12/2020,109840.09
14,Osbourne,Rawet,Male,50,Poland,Office Assistant III,8/12/2021,41511.02

In [15]:
count = len(employees.loc[(employees['sex'] == 'Female') & (employees['age'] < 50)])
count

5